services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    depends_on:
      - mongo
    env_file: ".env"
  
  semanticsearch:
    build:
      context: ./semanticsearch
      dockerfile: Dockerfile
    ports:
      - "8020:8020"
    volumes:
      - ./semanticsearch:/app
    depends_on:
      - mongo
      - backend
    env_file: ".env"

  elasticsearch:
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    ports:
      - "8030:8030"
    volumes:
      - ./elasticsearch:/app
    depends_on:
      - mongo
      - backend
    env_file: ".env"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    volumes:
      - ./front/src:/app/src
    depends_on:
      - backend
      - semanticsearch

  caddy:
    image: caddy:latest
    container_name: caddy
    ports: 
      - "80:80"
      - "443:443"
    volumes:
     - ./caddy/Caddyfile:/etc/caddy/Caddyfile
     - caddy_data:/data
     - caddy_config:/config
    depends_on:
      - frontend
      - backend
      - semanticsearch

  mongo:
    image: mongo:6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_CHATBOT_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/scripts/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    env_file: ".env"

volumes:
  mongo_data:
  caddy_data:
  caddy_config: