services:
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
    depends_on:
      - mongo
    env_file: ".env"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
        - 3000:3000
    volumes:
      - ./front:/app/app/
    depends_on:
      - backend

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  mongo:
    image: mongo:6
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_CHATBOT_DATABASE}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./database/scripts/setup.sh:/docker-entrypoint-initdb.d/setup.sh
    env_file: ".env"

volumes:
  mongo_data:
